'\" t
.TH RAINBOWPATH 1 2018-2019

.SH NAME

rainbowpath \- Color path components using a palette.

.SH SYNOPSIS

.B rainbowpath
[\fB\-p\fR \fIPALETTE\fR] [\fB\-s\fR \fISTYLE\fR] [\fB\-S\fR \fISEPARATOR\fR] [\fB\-m\fR \fIMETHOD\fR] [\fB\-l\fR] [\fB\-c\fR] [\fB\-n\fR] [\fB\-b\fR] [\fB\-h\fR] [\fB\-v\fR] [\fIPATH\fR]

\fBrainbowpath\fR formats supplied path by coloring each path component with a
color selected from a palette. By default, colors for path components are
selected based on the order they appear in the palette. If no palette is
supplied a default one will be used. When invoked without a path
\fBrainbowpath\fR displays the current working directory.

.SH OPTIONS

.TP
.BI \-p " PALETTE\fR,\fP " \-\-palette " PALETTE"
Semicolon-separated list of styles for path components.

.TP
.BI \-s " STYLE\fR,\fP " \-\-separator " STYLE"
Style for path separators.

.TP
.BI \-S " SEPARATOR\fR,\fP " \-\-separator\-string " SEPARATOR"
String used to separate path components in the output (defaults to '\fI/\fR').

.TP
.BI \-m " METHOD\fR,\fP " \-\-method " METHOD"

Method for selecting styles from palette. One of \fIsequential\fR, \fIhash\fR,
\fIrandom\fR (defaults to \fIsequential\fR). \fIsequential\fR mode selects
styles based on the order they appear in the palette. \fIhash\fR mode selects
styles based on the contents of path segment being processed. \fIrandom\fR mode
selects styles randomly from the palette.

.TP
.BR \-l ", " \-\-leading
Do not display leading path separator.

.TP
.BR \-c ", " \-\-compact
Replace home directory path prefix with \fI~\fR.

.TP
.BR \-n ", " \-\-newline
Do not append newline.

.TP
.BR \-b ", " \-\-bash
Escape control codes for use in Bash prompts.

.TP
.BR \-h ", " \-\-help
Display help.

.TP
.BR \-v ", " \-\-version
Display version information.

.SH STYLES

Styles specify how path components should look. \fB\-\-palette\fR and
\fB\-\-separator\fR options accept styles as arguments. Style consists of a list
of properties separated by commas. The possible properties are:

.RS
.TS
lB lB
l l.
Property	Description
fg=\fICOLOR\fR	Set text color to \fICOLOR\fR
bg=\fICOLOR\fR	Set background color to \fICOLOR\fR
bold	Bold font
dim	Dim color
underlined	Underlined text
blink	Blinking text
.TE
.RE

Where \fICOLOR\fR is an integer between \fI0\fR and \fI255\fR.

For example, the following invocation will display the current working
directory's path altering path components' styles between underlined green
(\fI2\fR) and bold yellow (\fI3\fR) on magenta (\fI5\fR) background:

.nf
rainbowpath --palette 'fg=2,underlined;fg=3,bg=5,bold'
.fi

.SH AUTHORS
Samuel Laurén <samuel.lauren@iki.fi>
