language: c
sudo: required
jobs:
  include:
    - stage: test
      script:
        - ./autogen.sh
        - ./configure --without-curses
        - make check
    - stage: binary
      services:
        - docker
      before_install:
        - mkdir rainbowpath-${TRAVIS_TAG:-untagged}
        - docker pull soft/rainbowpath-builder
        - docker run -it -d --name builder -v $(pwd):/home/builder/work soft/rainbowpath-builder sh
      script:
        - docker exec builder autoreconf -vfi
        - docker exec builder sh -c "CFLAGS='-static -O2' PKG_CONFIG='pkg-config --static' ./configure --with-curses"
        - docker exec builder make
        - docker cp builder:/home/builder/work/src/rainbowpath rainbowpath-${TRAVIS_TAG:-untagged}/rainbowpath
        - strip rainbowpath-${TRAVIS_TAG:-untagged}/rainbowpath
        - cp LICENSE README.md rainbowpath-${TRAVIS_TAG:-untagged}
        - tar -cvzf rainbowpath.tar.gz rainbowpath-${TRAVIS_TAG:-untagged}
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: rainbowpath.tar.gz
        skip_cleanup: true
        on:
          tags: true
