language: c
sudo: required
jobs:
  include:
    - stage: test
      script:
        - ./autogen.sh
        - ./configure --without-curses
        - make
        - ./src/rainbowpath
    - stage: binary
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y musl-tools libncurses-dev
      script:
        - ./autogen.sh
        - CC=musl-gcc CFLAGS="-static -O2" ./configure --with-curses
        - make
        - strip ./src/rainbowpath
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: ./src/rainbowpath
        skip_cleanup: true
        on:
          tags: true
