language: c
sudo: required
jobs:
  include:
    - stage: binary
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y musl-tools
      script:
        - ./autogen.sh
        - CC=musl-gcc CFLAGS=-static ./configure
        - make
        - strip rainbowpath
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: rainbowpath
        skip_cleanup: true
